### ISSUE TITLE
Aggregation mechanism for balances, via stats.

### ISSUE THREAD

**Issue by muxalko** [cgrates/cgrates#877]
Hello Dear CGRateS Team!
It is useful feature, to have account aggregation mechanism for balances, via stats? 
There are plenty campaigns that can be run on top of it, also usage reports/thresholds.

Thanks,
Michael

**Comment by Edwardro22** [comment]
Greetings @muxalko 
We have implemented in master *sum and *average for any field name (you can find sample config here: https://github.com/cgrates/cgrates/blob/master/data/tariffplans/testtp/Stats.csv). 
Please test it and let us know if it helps.

**Comment by danbogos** [comment]
hi @muxalko 

Since there was no feedback in the last month, we will consider the feature completed and close the issue.

DanB

**Comment by muxalko** [comment]
Hello Guys,
Sorry for is taking me so long to check, but, it is not very intuitive from the example CSV.
Still cannot figure it out, how to configure stats correctly.

The most confusing part is that both Stats and Threshold uses FilterIds , which one should reference  it ?
What are the steps for creating notification of 75% usage ?
Is that possible at all with current features ?

Thanks in advance,
Michael,

**Comment by danbogos** [comment]
Hey Michael,

The principle is simple, you will use *sum or *average in order to sum/average all the elements in queue. The value needs to be float and will be taken from the field specified in MetricParams.
In the sample we sent, you can find in MetricParams "Value" because that will be the header of the balances aggregated.

Let me know if still not clear.

DanB

**Comment by muxalko** [comment]
Hello Dan,
I feel like a dumb, the more I mess with it , more questions I got :)
Just to clarify, where should the filter with balance value go?
As I understand, There should be two filters.
1. Stats's Filter should be matching my Account,
2. Threshold's Filter should be on specific balance value, which will trigger an action?

I mean  :

Filters.csv
```
#Tenant[0],ID[1],FilterType[2],FilterFieldName[3],FilterFieldValues[4],ActivationInterval[5]
golant,FLTR_972536213067,*string,Account,972536213067,2017-08-01T00:00:00Z
golant,FLTR_DATA_USAGE_75,*string,EventType,BalanceUpdate,
golant,FLTR_DATA_USAGE_75,*string,BalanceID,data,
golant,FLTR_DATA_USAGE_75,*lt,Units,1000000000.0, 
```

Stats.csv - this is where I count my summary
```
#Tenant[0],Id[1],FilterIDs[2],ActivationInterval[3],QueueLength[4],TTL[5],Metrics[6],MetricParams[7],Blocker[8],Stored[9],Weight[10],MinItems[11],ThresholdIDs[12]
golant,STS_972536213067,FLTR_972536213067,2017-08-01T00:00:00Z,100,1s,*sum;*average,Value,true,true,20,2,THD_DATA_USAGE_75
```

Thresholds.csv - this is where I want to check my summary is at certain level 
```
#Tenant[0],Id[1],FilterIDs[2],ActivationInterval[3],Recurrent[4],MinHits[5],MinSleep[6],Blocker[7],Weight[8],ActionIDs[9],Async[10]
golant,THD_DATA_USAGE_75,FLTR_DATA_USAGE_75,2017-08-01T00:00:00Z,true,1,1s,false,10,LOG_WARNING_DATA_USAGE_75,true
```

If that is correct, then, I can't understand where is the "Value" param taken from, and when.
I was expecting Units/Cost/Usage to be here, and , summed at processEvent, just as in the thresholds.
Is that taken from the account balance itself ? 


 I am trying to test but, cant' figure out why isn't sum is updating:
```
{
  "id":"0",
  "jsonrpc":"2.0",
  "method":"StatSv1.GetStatQueuesForEvent",
  "params":[
   {
   "Tenant": "golant",
		"ID": "a0e8f0d2-62fa-4302-a51b-aaedaa9158f5",
		"Context": null,
		"Time": null,
		"Event": {
			"Account": "972536213067",
			"BalanceID": "data",
			"EventSource": "BalanceUpdate",
			"EventType": "BalanceUpdate",
			"Units": 100000000.0
		}
    }
  ]
}

{
"id": "0",
"result":[
{
"Tenant": "golant",
"ID": "STS_972536213067",
"SQItems":[],
"SQMetrics":{
"*sum":{
"Sum": 0,
"Events":{},
"MinItems": 2,
"FieldName": "Value"
}
},
"MinItems": 0
}
],
"error": null
}
```


I was trying normal data session (init,update,terminate) , but my metric isn't updated, although threshold seem to be hit.

Here is **GetQueueFloatMetrics** response:
```
{
  "id":"0",
  "jsonrpc":"2.0",
  "method":"StatSv1.GetQueueFloatMetrics",
  "params":[
   {
     "ID": "STS_972536213067",
    "Tenant":"golant"
   
    }
  ]
}

{
"id": "0",
"result":{
"*sum": -1
},
"error": null
}
```

Here is reply of **ApierV1.GetStatQueueProfile**
```

{
  "id":"0",
  "jsonrpc":"2.0",
  "method":"ApierV1.GetStatQueueProfile",
  "params":[
    {
      "ID" :"STS_972536213067",
    "Tenant":"golant"

    }
  ]
}
{
    "id": "0",
    "result": {
        "Tenant": "golant",
        "ID": "STS_972536213067",
        "FilterIDs": [
            "FLTR_972536213067"
        ],
        "ActivationInterval": {
            "ActivationTime": "2017-08-01T00:00:00Z",
            "ExpiryTime": "0001-01-01T00:00:00Z"
        },
        "QueueLength": 100,
        "TTL": 1000000000,
        "Metrics": [
            {
                "MetricID": "*sum",
                "Parameters": "Value"
            }
        ],
        "ThresholdIDs": [
            "THD_DATA_USAGE_75"
        ],
        "Blocker": true,
        "Stored": true,
        "Weight": 20,
        "MinItems": 2
    },
    "error": null
}
```

**GetThresholdProfile :**
```
{
  "id":"0",
  "method":"ApierV1.GetThresholdProfile",
  "params":[
    {
      "Tenant":"golant",
      "ID":"THD_DATA_USAGE_75"
    }
  ]
}
{
"id": "0",
"result":{
"Tenant": "golant",
"ID": "THD_DATA_USAGE_75",
"FilterIDs":[
"FLTR_DATA_USAGE_75"
],
"ActivationInterval":{
"ActivationTime": "2017-08-01T00:00:00Z",
"ExpiryTime": "0001-01-01T00:00:00Z"
},
"Recurrent": false,
"MinHits": 1,
"MinSleep": 1000000000,
"Blocker": false,
"Weight": 10,
"ActionIDs":[
"LOG_WARNING_DATA_USAGE_75"
],
"Async": false
},
"error": null
}
```


**GetThresholdsForEvent :**
```
{
  "id":"0",
  "method":"ThresholdSv1.GetThresholdsForEvent",
  "params":[
    {
    "Tenant": "golant",
		"ID": "a0e8f0d2-62fa-4302-a51b-aaedaa9158f5",
		"Context": null,
		"Time": null,
		"Event": {
			"Account": "972536213067",
			"BalanceID": "data",
			"EventSource": "AccountS",
			"EventType": "BalanceUpdate",
			"Units": 100000000.0
		}

    }
  ]
}

{
"id": "0",
"result":[
{
"Tenant": "golant",
"ID": "THD_972536213067",
"Hits": 22,
"Snooze": "2018-02-20T00:44:42.59282907+02:00"
}
],
"error": null
}
```


Please help,
Thanks,
Michael

**Comment by danbogos** [comment]
Hey Michael,

It is not you, it is me :), I have forgotten we use Units in Balance events. You should *sum the "Units" in that case and not "Value".
After stats is built, you configure thresholds like you do for the others, it should be no difference (monitoring *sum value).

DanB

**Comment by muxalko** [comment]
Dan,
What is the meaning of "MinItems": 2 ?

**Comment by danbogos** [comment]
Michael,

Can we brig the discussion on google group? So others can also benefit out of it.

Thanks,
Dan
