### ISSUE TITLE
Freeswitch "cgr_usage" variable. Issue with least_cost 

### ISSUE THREAD

**Issue by arsperger** [cgrates/cgrates#995]
Hi guys,

Please add cgr_usage vaiable in Freeswich events.

More details about the issue in this thread:
https://groups.google.com/forum/#!topic/cgrates/sVBC5jzrG40

Thanks,
Arsen Semionov.

**Comment by arsperger** [comment]
The issue has been fixed in commit  0a94cd76f0836
Usage is hard-coded to 1m

**Comment by danbogos** [comment]
@arsperger 

As discussed on google group, we still not have the dynamic behavior by hardcoding, so will leave the issue opened till we implement the dynamic functionality.

DanB

**Comment by TeoV** [comment]
Hi arsperger,
This features is availabele in master .
Please come back if any issues.

Thanks,
TeoV

**Comment by arsperger** [comment]
Hey guys,

which variable I need to set?

I am trying to set cgr_usage but it doesn't work.

variable_cgr_usage: 1m
variable_current_application: park

I sill see  "Usage":0 in SupplierSv1.GetSuppliers ?

**Comment by TeoV** [comment]
Hi Arsen,
Instead of cgr_usage we have cgr_acd .
<variable name="cgr_acd" value="30"/> 

Thanks,
TeoV

**Comment by arsperger** [comment]
great, works now, thank you Teo.
